AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    Properties:
      Name: myapikey
      Description: API Key for dev-ec2-create
      Enabled: true

  UsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    Properties:
      Description: Usage Plan for dev-ec2-create
      ApiStages:
        - ApiId: <existing-api-gateway-id>
          Stage: dev
      Quota:
        Limit: 1000
        Offset: 2
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 5

  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
