service: ec2-create

package:
  exclude:
    - '**'
  include:
    - 'handler.py'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  vpc:
    subnetIds:
      - ${file(./terraform/variables.json):private_subnet_id.value}  # Update the path
    securityGroupIds:
      - ${file(./terraform/variables.json):security_group_id.value}  # Update the path
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:RunInstances"
        - "ec2:DescribeInstances"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeSecurityGroups"
        - "ec2:CreateNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:CreateTags"
      Resource: "*"

functions:
  createInstance:
    handler: handler.create_instance
    timeout: 30  # Reduce to 30 seconds to match API Gateway limit
    events:
      - http:
          path: create
          method: post
          private: true
          cors: true
